// Auto-generated by scripts/build-quiz-database.mjs
// Lightweight starter pool (40 questions across 8 languages) for instant zero-fetch homepage interaction
import type { QuizQuestion } from './types';

export const starterQuestions: QuizQuestion[] = [
  {
    "id": "js-001",
    "language": "javascript",
    "difficulty": "easy",
    "concepts": [
      "arrays",
      "references",
      "mutability"
    ],
    "code": "const a = [1, 2, 3];\nconst b = a;\n\nb.push(4);\nconsole.log(a.length);",
    "question": "What will be the output?",
    "options": [
      "3",
      "4",
      "undefined",
      "Error"
    ],
    "correctAnswer": "4",
    "explanation": "`a` and `b` reference the exact same array in memory. Mutating the array via `b.push(4)` directly modifies the shared array, so `a.length` is 4.",
    "runtime": "Modern ECMAScript",
    "hint": "Does assignment (=) for objects create a new copy or copy the memory reference?",
    "walkthrough": [
      {
        "step": 1,
        "label": "Array allocation",
        "explanation": "`a` is assigned a reference to `[1, 2, 3]` in the heap.",
        "highlightLine": 1
      },
      {
        "step": 2,
        "label": "Reference copy",
        "explanation": "`b` receives a copy of the reference pointing to the same array.",
        "highlightLine": 2
      },
      {
        "step": 3,
        "label": "Mutation",
        "explanation": "`b.push(4)` appends 4 to that shared array.",
        "highlightLine": 4
      },
      {
        "step": 4,
        "label": "Inspection",
        "explanation": "`a.length` reads the length of the mutated array, which is now 4.",
        "highlightLine": 5
      }
    ]
  },
  {
    "id": "js-002",
    "language": "javascript",
    "difficulty": "easy",
    "concepts": [
      "types",
      "typeof"
    ],
    "code": "console.log(typeof null);",
    "question": "What will be the output?",
    "options": [
      "\"null\"",
      "\"undefined\"",
      "\"object\"",
      "\"boolean\""
    ],
    "correctAnswer": "\"object\"",
    "explanation": "In JavaScript, `typeof null === 'object'` is a historic legacy bug dating back to the very first JS implementation where values had a type tag in the lower bits, and 0 represented an object reference.",
    "runtime": "Modern ECMAScript",
    "hint": "Think about the famous legacy quirk in JavaScript's type representation."
  },
  {
    "id": "js-003",
    "language": "javascript",
    "difficulty": "easy",
    "concepts": [
      "coercion",
      "arrays",
      "operators"
    ],
    "code": "console.log([1, 2] + [3, 4]);",
    "question": "What will be the output?",
    "options": [
      "[1, 2, 3, 4]",
      "\"1,23,4\"",
      "\"1,2,3,4\"",
      "NaN"
    ],
    "correctAnswer": "\"1,23,4\"",
    "explanation": "When using the `+` operator on arrays, both arrays are coerced to primitives by calling `.toString()`, yielding `\"1,2\"` and `\"3,4\"`. Concatenating them results in `\"1,23,4\"`.",
    "runtime": "Modern ECMAScript",
    "hint": "How does the plus operator behave when applied to arrays rather than numbers?"
  },
  {
    "id": "js-004",
    "language": "javascript",
    "difficulty": "easy",
    "concepts": [
      "numbers",
      "floating-point",
      "equality"
    ],
    "code": "console.log(0.1 + 0.2 === 0.3);",
    "question": "What will be the output?",
    "options": [
      "true",
      "false",
      "undefined",
      "TypeError"
    ],
    "correctAnswer": "false",
    "explanation": "JavaScript numbers use IEEE 754 double-precision binary floating-point. `0.1 + 0.2` evaluates to `0.30000000000000004`, which is strictly not equal to `0.3`.",
    "runtime": "Modern ECMAScript",
    "hint": "Can binary floating-point numbers represent 0.1 and 0.2 with exact precision?"
  },
  {
    "id": "js-005",
    "language": "javascript",
    "difficulty": "medium",
    "concepts": [
      "hoisting",
      "scope",
      "var"
    ],
    "code": "var x = 10;\n\nfunction check() {\n  console.log(x);\n  var x = 20;\n}\n\ncheck();",
    "question": "What will be the output?",
    "options": [
      "10",
      "20",
      "undefined",
      "ReferenceError"
    ],
    "correctAnswer": "undefined",
    "explanation": "Inside `check()`, `var x` is hoisted to the top of the function scope initialized with `undefined`. The local declaration shadows the global `x`, so `undefined` is logged before assignment.",
    "runtime": "Modern ECMAScript",
    "hint": "Variable declarations with `var` are hoisted to the top of their enclosing function."
  },
  {
    "id": "py-001",
    "language": "python",
    "difficulty": "medium",
    "concepts": [
      "functions",
      "default-arguments",
      "mutability"
    ],
    "code": "def add_item(val, items=[]):\n    items.append(val)\n    return items\n\nadd_item(1)\nprint(add_item(2))",
    "question": "What will be the output?",
    "options": [
      "[2]",
      "[1, 2]",
      "[1]",
      "TypeError"
    ],
    "correctAnswer": "[1, 2]",
    "explanation": "Default parameter values in Python are evaluated once when the function is defined, not each time it is called. The list `items` is retained and reused across calls.",
    "runtime": "Python 3.10+",
    "hint": "Are default arguments re-initialized on every invocation in Python?",
    "walkthrough": [
      {
        "step": 1,
        "label": "Function definition",
        "explanation": "`items` default list `[]` is created in memory once at function definition time.",
        "highlightLine": 1
      },
      {
        "step": 2,
        "label": "First call",
        "explanation": "`add_item(1)` appends 1 to that single shared list.",
        "highlightLine": 5
      },
      {
        "step": 3,
        "label": "Second call",
        "explanation": "`add_item(2)` appends 2 to the same list.",
        "highlightLine": 6
      },
      {
        "step": 4,
        "label": "Result",
        "explanation": "Returns `[1, 2]`.",
        "highlightLine": 6
      }
    ]
  },
  {
    "id": "py-002",
    "language": "python",
    "difficulty": "easy",
    "concepts": [
      "strings",
      "slicing"
    ],
    "code": "s = \"Python\"\nprint(s[::-1])",
    "question": "What will be the output?",
    "options": [
      "'nohtyP'",
      "'Python'",
      "'P'",
      "IndexError"
    ],
    "correctAnswer": "'nohtyP'",
    "explanation": "A step of `-1` in extended slice notation `[start:stop:step]` reverses the sequence.",
    "runtime": "Python 3.10+"
  },
  {
    "id": "py-003",
    "language": "python",
    "difficulty": "medium",
    "concepts": [
      "identity",
      "caching",
      "integers"
    ],
    "code": "a = 256\nb = 256\nc = 300\nd = 300\nprint(a is b, c is d)",
    "question": "What will be the output in standard CPython REPL?",
    "options": [
      "True False",
      "True True",
      "False False",
      "False True"
    ],
    "correctAnswer": "True False",
    "explanation": "CPython pre-allocates and caches small integers in the range [-5, 256]. Thus `256 is 256` evaluates to `True`, but `300` creates separate heap objects in interactive evaluation.",
    "runtime": "CPython 3"
  },
  {
    "id": "py-004",
    "language": "python",
    "difficulty": "medium",
    "concepts": [
      "lists",
      "multiplication",
      "shallow-copy"
    ],
    "code": "grid = [[0]] * 3\ngrid[0].append(1)\nprint(grid)",
    "question": "What will be the output?",
    "options": [
      "[[0, 1], [0], [0]]",
      "[[0, 1], [0, 1], [0, 1]]",
      "[[0], [0], [0, 1]]",
      "IndexError"
    ],
    "correctAnswer": "[[0, 1], [0, 1], [0, 1]]",
    "explanation": "List multiplication `[[0]] * 3` copies the inner list reference 3 times rather than creating deep copies. Mutating `grid[0]` reflects in all elements.",
    "runtime": "Python 3.10+"
  },
  {
    "id": "py-005",
    "language": "python",
    "difficulty": "easy",
    "concepts": [
      "tuples",
      "syntax"
    ],
    "code": "x = (1)\ny = (1,)\nprint(type(x) == type(y))",
    "question": "What will be the output?",
    "options": [
      "False",
      "True",
      "TypeError",
      "SyntaxError"
    ],
    "correctAnswer": "False",
    "explanation": "`x = (1)` is simply an integer in parentheses (type `int`). To create a single-element tuple, a trailing comma is required: `y = (1,)` (type `tuple`).",
    "runtime": "Python 3.10+"
  },
  {
    "id": "java-001",
    "language": "java",
    "difficulty": "easy",
    "concepts": [
      "strings",
      "string-pool",
      "equality"
    ],
    "code": "String s1 = \"Java\";\nString s2 = new String(\"Java\");\nSystem.out.println(s1 == s2);",
    "question": "What will be the output?",
    "options": [
      "false",
      "true",
      "null",
      "Compilation error"
    ],
    "correctAnswer": "false",
    "explanation": "`==` tests reference equality. `s1` refers to the string literal in the string intern pool, whereas `new String(...)` allocates an explicit new object in the heap.",
    "runtime": "Java 17+"
  },
  {
    "id": "java-002",
    "language": "java",
    "difficulty": "medium",
    "concepts": [
      "strings",
      "intern",
      "string-pool"
    ],
    "code": "String s1 = \"Java\";\nString s2 = new String(\"Java\").intern();\nSystem.out.println(s1 == s2);",
    "question": "What will be the output?",
    "options": [
      "true",
      "false",
      "null",
      "Compilation error"
    ],
    "correctAnswer": "true",
    "explanation": "Calling `.intern()` returns the canonical representation from the string pool, which matches the reference of `s1`.",
    "runtime": "Java 17+"
  },
  {
    "id": "java-003",
    "language": "java",
    "difficulty": "easy",
    "concepts": [
      "operators",
      "integer-division"
    ],
    "code": "int a = 5 / 2;\ndouble b = 5 / 2;\nSystem.out.println(a + \" \" + b);",
    "question": "What will be the output?",
    "options": [
      "2 2.0",
      "2 2.5",
      "2.5 2.5",
      "2.0 2.0"
    ],
    "correctAnswer": "2 2.0",
    "explanation": "Both operands of `5 / 2` are integer literals, performing integer truncation to 2. Assigning 2 to `double b` converts it to `2.0`.",
    "runtime": "Java 17+"
  },
  {
    "id": "java-004",
    "language": "java",
    "difficulty": "medium",
    "concepts": [
      "autoboxing",
      "integer-cache"
    ],
    "code": "Integer a = 100, b = 100;\nInteger c = 200, d = 200;\nSystem.out.println((a == b) + \" \" + (c == d));",
    "question": "What will be the output?",
    "options": [
      "true false",
      "true true",
      "false false",
      "false true"
    ],
    "correctAnswer": "true false",
    "explanation": "Java caches boxed Integer instances for values between -128 and 127. Values outside this range (such as 200) create separate instances in heap memory.",
    "runtime": "Java 17+"
  },
  {
    "id": "java-005",
    "language": "java",
    "difficulty": "medium",
    "concepts": [
      "exceptions",
      "finally",
      "control-flow"
    ],
    "code": "static int getVal() {\n    int x = 1;\n    try {\n        return x;\n    } finally {\n        x = 2;\n    }\n}\nSystem.out.println(getVal());",
    "question": "What will be the output?",
    "options": [
      "1",
      "2",
      "0",
      "Compilation error"
    ],
    "correctAnswer": "1",
    "explanation": "The value of primitive `x` (1) is copied to the return register before the `finally` block executes. Modifying the local variable `x` afterwards has no effect on the returned value.",
    "runtime": "Java 17+"
  },
  {
    "id": "c-001",
    "language": "c",
    "difficulty": "easy",
    "concepts": [
      "pointers",
      "arrays",
      "pointer-arithmetic"
    ],
    "code": "int arr[] = {10, 20, 30};\nint *p = arr;\np++;\nprintf(\"%d\", *p);",
    "question": "What will be printed?",
    "options": [
      "20",
      "10",
      "30",
      "Compilation error"
    ],
    "correctAnswer": "20",
    "explanation": "`p` initially points to `arr[0]` (10). Incrementing `p++` advances the pointer to the next integer element `arr[1]`, whose value is 20.",
    "runtime": "C99 / C11 / C17"
  },
  {
    "id": "c-002",
    "language": "c",
    "difficulty": "medium",
    "concepts": [
      "pointers",
      "precedence",
      "post-increment"
    ],
    "code": "int a[] = {10, 20, 30};\nint *p = a;\nprintf(\"%d \", *p++);\nprintf(\"%d\", *p);",
    "question": "What will be printed?",
    "options": [
      "10 20",
      "20 20",
      "10 10",
      "11 20"
    ],
    "correctAnswer": "10 20",
    "explanation": "Post-increment `*p++` has postfix precedence: it yields the dereferenced current pointer value (10) and then increments pointer `p` to point to the next element (20).",
    "runtime": "C99 / C11 / C17"
  },
  {
    "id": "c-003",
    "language": "c",
    "difficulty": "medium",
    "concepts": [
      "strings",
      "null-terminator",
      "strlen"
    ],
    "code": "char str[] = \"abc\\0def\";\nprintf(\"%zu\", strlen(str));",
    "question": "What will be printed?",
    "options": [
      "3",
      "7",
      "6",
      "8"
    ],
    "correctAnswer": "3",
    "explanation": "`strlen()` measures characters up to the first null byte `\\0`. It stops after `'abc'`, returning length 3.",
    "runtime": "C99 / C11 / C17"
  },
  {
    "id": "c-004",
    "language": "c",
    "difficulty": "medium",
    "concepts": [
      "operators",
      "short-circuit",
      "side-effects"
    ],
    "code": "int a = 0, b = 5;\nif (a && ++b) {\n    // nothing\n}\nprintf(\"%d\", b);",
    "question": "What will be printed?",
    "options": [
      "5",
      "6",
      "0",
      "1"
    ],
    "correctAnswer": "5",
    "explanation": "In logical AND (`&&`), if the left operand evaluates to 0 (false), the right operand is short-circuited and not evaluated. `++b` never runs.",
    "runtime": "C99 / C11 / C17"
  },
  {
    "id": "c-005",
    "language": "c",
    "difficulty": "medium",
    "concepts": [
      "switch",
      "fallthrough"
    ],
    "code": "int x = 2;\nswitch (x) {\n    case 1: x += 1;\n    case 2: x += 2;\n    case 3: x += 3;\n}\nprintf(\"%d\", x);",
    "question": "What will be printed?",
    "options": [
      "7",
      "4",
      "2",
      "5"
    ],
    "correctAnswer": "7",
    "explanation": "Execution jumps to `case 2`, computing `x = 2 + 2 = 4`. Because there is no `break`, execution falls through to `case 3`, computing `x = 4 + 3 = 7`.",
    "runtime": "C99 / C11 / C17"
  },
  {
    "id": "cpp-001",
    "language": "cpp",
    "difficulty": "easy",
    "concepts": [
      "references",
      "functions",
      "pass-by-reference"
    ],
    "code": "void addTen(int &x) {\n    x += 10;\n}\n\nint a = 5;\naddTen(a);\nstd::cout << a;",
    "question": "What will be printed?",
    "options": [
      "15",
      "5",
      "10",
      "Compilation error"
    ],
    "correctAnswer": "15",
    "explanation": "Parameter `int &x` is passed by reference, binding directly to `a`. Mutating `x` modifies the original variable `a` to 15.",
    "runtime": "C++17 / C++20"
  },
  {
    "id": "cpp-002",
    "language": "cpp",
    "difficulty": "medium",
    "concepts": [
      "vector",
      "copy-semantics",
      "stl"
    ],
    "code": "std::vector<int> a = {1, 2};\nauto b = a;\nb.push_back(3);\nstd::cout << a.size() << \" \" << b.size();",
    "question": "What will be printed?",
    "options": [
      "2 3",
      "3 3",
      "2 2",
      "Compilation error"
    ],
    "correctAnswer": "2 3",
    "explanation": "In C++, `std::vector` possesses deep copy value semantics. `auto b = a` creates an independent copy; modifying `b` does not alter `a`.",
    "runtime": "C++17 / C++20"
  },
  {
    "id": "cpp-004",
    "language": "cpp",
    "difficulty": "medium",
    "concepts": [
      "lambdas",
      "capture-by-value",
      "mutable"
    ],
    "code": "int x = 10;\nauto fn = [x]() mutable {\n    return ++x;\n};\nfn();\nstd::cout << x;",
    "question": "What will be printed?",
    "options": [
      "10",
      "11",
      "Compilation error",
      "0"
    ],
    "correctAnswer": "10",
    "explanation": "Capture `[x]` copies `x` by value into the lambda's closure. The `mutable` keyword allows modifying the captured copy, leaving outer `x` unchanged at 10.",
    "runtime": "C++17 / C++20"
  },
  {
    "id": "cpp-005",
    "language": "cpp",
    "difficulty": "medium",
    "concepts": [
      "range-for",
      "copy-vs-reference"
    ],
    "code": "std::vector<int> v = {1, 2};\nfor (auto x : v) {\n    x *= 2;\n}\nstd::cout << v[0];",
    "question": "What will be printed?",
    "options": [
      "1",
      "2",
      "0",
      "Compilation error"
    ],
    "correctAnswer": "1",
    "explanation": "`for (auto x : v)` iterates by value, copying each element into `x`. Modifying `x` does not update the vector elements; `for (auto &x : v)` would be required.",
    "runtime": "C++17 / C++20"
  },
  {
    "id": "cpp-006",
    "language": "cpp",
    "difficulty": "easy",
    "concepts": [
      "strings",
      "concatenation"
    ],
    "code": "std::string s = \"A\";\ns += \"B\";\nstd::cout << s;",
    "question": "What will be printed?",
    "options": [
      "AB",
      "A",
      "B",
      "Compilation error"
    ],
    "correctAnswer": "AB",
    "explanation": "`+=` appends string 'B' to 'A'.",
    "runtime": "C++17 / C++20",
    "hint": "Think about C++ semantics for strings."
  },
  {
    "id": "kt-001",
    "language": "kotlin",
    "difficulty": "easy",
    "concepts": [
      "nullability",
      "elvis-operator"
    ],
    "code": "val name: String? = null\nprintln(name ?: \"Default\")",
    "question": "What will be printed?",
    "options": [
      "Default",
      "null",
      "Compilation error",
      "NullPointerException"
    ],
    "correctAnswer": "Default",
    "explanation": "The Elvis operator `?:` evaluates the left operand; if it is null, it evaluates and returns the right operand ('Default').",
    "runtime": "Kotlin 1.9+"
  },
  {
    "id": "kt-002",
    "language": "kotlin",
    "difficulty": "medium",
    "concepts": [
      "scope-functions",
      "let",
      "safe-call"
    ],
    "code": "val str: String? = \"Kotlin\"\nval len = str?.let { it.length } ?: 0\nprintln(len)",
    "question": "What will be printed?",
    "options": [
      "6",
      "0",
      "null",
      "Compilation error"
    ],
    "correctAnswer": "6",
    "explanation": "Because `str` is not null, the safe call `?.` invokes `let`, executing `it.length` which produces 6.",
    "runtime": "Kotlin 1.9+"
  },
  {
    "id": "kt-003",
    "language": "kotlin",
    "difficulty": "medium",
    "concepts": [
      "data-classes",
      "copy",
      "equality"
    ],
    "code": "data class User(val id: Int, val name: String)\nval u1 = User(1, \"Alice\")\nval u2 = u1.copy(name = \"Bob\")\nprintln(u1 == u2)",
    "question": "What will be printed?",
    "options": [
      "false",
      "true",
      "Compilation error",
      "null"
    ],
    "correctAnswer": "false",
    "explanation": "Data classes generate structural equality `equals()` comparing all primary constructor properties. Since `u1.name != u2.name`, `u1 == u2` is `false`.",
    "runtime": "Kotlin 1.9+"
  },
  {
    "id": "kt-004",
    "language": "kotlin",
    "difficulty": "easy",
    "concepts": [
      "val",
      "mutability",
      "collections"
    ],
    "code": "val list = mutableListOf(1, 2)\nlist.add(3)\nprintln(list.size)",
    "question": "What will be printed?",
    "options": [
      "3",
      "2",
      "Compilation error",
      "UnsupportedOperationException"
    ],
    "correctAnswer": "3",
    "explanation": "`val` guarantees reference immutability (the variable `list` cannot be reassigned to a new list), but the underlying `MutableList` instance itself remains mutable.",
    "runtime": "Kotlin 1.9+"
  },
  {
    "id": "kt-005",
    "language": "kotlin",
    "difficulty": "medium",
    "concepts": [
      "scope-functions",
      "apply"
    ],
    "code": "val items = mutableListOf<Int>().apply {\n    add(10)\n    add(20)\n}\nprintln(items.sum())",
    "question": "What will be printed?",
    "options": [
      "30",
      "20",
      "10",
      "Compilation error"
    ],
    "correctAnswer": "30",
    "explanation": "`apply` executes the lambda block with the context object as receiver `this`, and returns the context object itself. The sum of 10 + 20 is 30.",
    "runtime": "Kotlin 1.9+"
  },
  {
    "id": "swift-001",
    "language": "swift",
    "difficulty": "easy",
    "concepts": [
      "structs",
      "value-semantics",
      "copy-on-write"
    ],
    "code": "struct Point {\n    var x: Int\n}\nvar p1 = Point(x: 10)\nvar p2 = p1\np2.x = 20\nprint(p1.x)",
    "question": "What will be printed?",
    "options": [
      "10",
      "20",
      "0",
      "Compilation error"
    ],
    "correctAnswer": "10",
    "explanation": "In Swift, `struct` types have value semantics. Assigning `var p2 = p1` makes an independent copy; modifying `p2.x` does not alter `p1.x`.",
    "runtime": "Swift 5.9+"
  },
  {
    "id": "swift-002",
    "language": "swift",
    "difficulty": "medium",
    "concepts": [
      "classes",
      "reference-semantics"
    ],
    "code": "class Node {\n    var value: Int\n    init(_ v: Int) { self.value = v }\n}\nvar n1 = Node(10)\nvar n2 = n1\nn2.value = 20\nprint(n1.value)",
    "question": "What will be printed?",
    "options": [
      "20",
      "10",
      "0",
      "Compilation error"
    ],
    "correctAnswer": "20",
    "explanation": "Swift `class` types have reference semantics. `n1` and `n2` point to the identical instance in memory; changing `n2.value` directly modifies `n1.value`.",
    "runtime": "Swift 5.9+"
  },
  {
    "id": "swift-003",
    "language": "swift",
    "difficulty": "easy",
    "concepts": [
      "optionals",
      "nil-coalescing"
    ],
    "code": "var name: String? = nil\nprint(name ?? \"Guest\")",
    "question": "What will be printed?",
    "options": [
      "Guest",
      "nil",
      "Optional(\"Guest\")",
      "Compilation error"
    ],
    "correctAnswer": "Guest",
    "explanation": "The nil-coalescing operator `??` unwraps an optional if it has a value, or provides a default fallback string ('Guest') when it is `nil`.",
    "runtime": "Swift 5.9+"
  },
  {
    "id": "swift-004",
    "language": "swift",
    "difficulty": "medium",
    "concepts": [
      "defer",
      "lifo-order"
    ],
    "code": "func run() {\n    defer { print(\"A\", terminator: \"\") }\n    defer { print(\"B\", terminator: \"\") }\n    print(\"C\", terminator: \"\")\n}\nrun()",
    "question": "What will be printed?",
    "options": [
      "CBA",
      "CAB",
      "ABC",
      "BCA"
    ],
    "correctAnswer": "CBA",
    "explanation": "Statements in `defer` blocks execute upon function exit in reverse (LIFO - Last In First Out) order. 'C' prints first, followed by 'B', then 'A'.",
    "runtime": "Swift 5.9+"
  },
  {
    "id": "swift-005",
    "language": "swift",
    "difficulty": "medium",
    "concepts": [
      "property-observers",
      "didSet"
    ],
    "code": "var count = 0 {\n    didSet {\n        count += 1\n    }\n}\ncount = 5\nprint(count)",
    "question": "What will be printed?",
    "options": [
      "6",
      "5",
      "0",
      "Infinite loop"
    ],
    "correctAnswer": "6",
    "explanation": "`count = 5` triggers the `didSet` observer. Setting `count += 1` inside its own `didSet` does not trigger further recursive observer calls in Swift, ending with 6.",
    "runtime": "Swift 5.9+"
  },
  {
    "id": "dart-001",
    "language": "dart",
    "difficulty": "easy",
    "concepts": [
      "cascade-operator",
      "lists"
    ],
    "code": "var list = [3, 1, 2]..sort();\nprint(list);",
    "question": "What will be printed?",
    "options": [
      "[1, 2, 3]",
      "[3, 1, 2]",
      "null",
      "Compilation error"
    ],
    "correctAnswer": "[1, 2, 3]",
    "explanation": "The cascade operator `..` performs a sequence of operations on an object and returns the receiver itself (the sorted `list`).",
    "runtime": "Dart 3.0+"
  },
  {
    "id": "dart-002",
    "language": "dart",
    "difficulty": "medium",
    "concepts": [
      "null-safety",
      "null-aware-assignment"
    ],
    "code": "int? x;\nx ??= 10;\nx ??= 20;\nprint(x);",
    "question": "What will be printed?",
    "options": [
      "10",
      "20",
      "null",
      "Compilation error"
    ],
    "correctAnswer": "10",
    "explanation": "`??=` assigns a value only if the target is currently null. The first assignment sets `x = 10`; the second does nothing because `x` is no longer null.",
    "runtime": "Dart 3.0+"
  },
  {
    "id": "dart-003",
    "language": "dart",
    "difficulty": "medium",
    "concepts": [
      "const",
      "canonical-instances",
      "identity"
    ],
    "code": "const a = [1, 2];\nconst b = [1, 2];\nprint(identical(a, b));",
    "question": "What will be printed?",
    "options": [
      "true",
      "false",
      "Compilation error",
      "null"
    ],
    "correctAnswer": "true",
    "explanation": "In Dart, `const` values are canonicalized at compile-time into single shared instances in memory, making `identical(a, b)` evaluate to `true`.",
    "runtime": "Dart 3.0+"
  },
  {
    "id": "dart-004",
    "language": "dart",
    "difficulty": "easy",
    "concepts": [
      "spread-operator",
      "null-aware-spread"
    ],
    "code": "List<int>? extra;\nvar items = [1, 2, ...?extra];\nprint(items.length);",
    "question": "What will be printed?",
    "options": [
      "2",
      "3",
      "NullThrownError",
      "Compilation error"
    ],
    "correctAnswer": "2",
    "explanation": "The null-aware spread operator `...?` safely skips spreading if the collection operand is null, leaving `items` with 2 elements.",
    "runtime": "Dart 3.0+"
  },
  {
    "id": "dart-005",
    "language": "dart",
    "difficulty": "medium",
    "concepts": [
      "collection-if",
      "lists"
    ],
    "code": "bool promo = false;\nvar cart = ['Apple', if (promo) 'Discount'];\nprint(cart.length);",
    "question": "What will be printed?",
    "options": [
      "1",
      "2",
      "Compilation error",
      "null"
    ],
    "correctAnswer": "1",
    "explanation": "Collection `if` evaluates conditionally during list construction. Since `promo` is false, 'Discount' is not included.",
    "runtime": "Dart 3.0+"
  }
];
